# Generated by Django 5.1.5 on 2025-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbCategory',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tb_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbSchoolslg',
            fields=[
                ('id_schoolslg', models.AutoField(db_column='id_SchoolsLG', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=45)),
                ('latitude', models.DecimalField(decimal_places=0, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=0, max_digits=50)),
            ],
            options={
                'db_table': 'tb_schoolslg',
                'managed': False,
            },
        ),
    ]
