# Generated by Django 5.1.5 on 2025-01-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escolas_loc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField(unique=True)),
                ('longitude', models.FloatField(unique=True)),
            ],
        ),
    ]
