# Generated by Django 5.1.5 on 2025-01-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localizaLG_app', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbschoolslg',
            options={},
        ),
    ]
