# Generated by Django 5.1.5 on 2025-01-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localizaLG_app', '0003_alter_tbschoolslg_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbschoolslg',
            options={'managed': False},
        ),
    ]
