# Generated by Django 5.1.5 on 2025-01-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localizaLG_app', '0004_alter_tbschoolslg_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbcategory',
            table='tbcategory',
        ),
        migrations.AlterModelTable(
            name='tbschoolslg',
            table='tbschoolslg',
        ),
    ]
